spring :
  datasource:
    url: jdbc:mysql://localhost:3306/mosburger_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


  mail:
    host: smtp.gmail.com
    port: 587
    username: nisanduab@gmail.com
    password: hesw fonp vqez ziwv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true